language: scala
scala:
  - 2.12.4

cache:
  timeout: 600
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/build/peterbecich/BannoDemo/target

script:
  - sbt compile
  - sbt test
  - sbt docker
    
jdk:
  - openjdk8

git:
  submodules: false
  
